name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  integration:
    name: Run Continuous integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

  todo:
    name: Disallow TODOs and FIXMEs inside source-code.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        VAR=$( ! grep --exclude-dir={.git,.github,vendor} -rE "TODO|FIXME")
        if [ $? -gt 0 ] ; then
          echo -e "Commits with TODO/FIXME in source-code is not allowed:"
          echo -e "${VAR}" | (TAB=$'\t'; sed "s/^/$TAB/" )
          exit 1
        else
          echo "All good. No TODOS/FIXMEs found."
        fi
